"""add unique constraint to trip_followers

Revision ID: 66d64fb312ff
Revises: add_user_features
Create Date: 2026-08-31 00:46:06.208548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66d64fb312ff'
down_revision = 'add_user_features'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_followers', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_trip_followers_user_trip', ['user_id', 'trip_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_followers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_trip_followers_user_trip', type_='unique')

    # ### end Alembic commands ###
